using System.Collections.Generic;
using UnityEngine;

public class PlatformController : MonoBehaviour
{
    [Header("Configuraci贸n de las plataformas")]
    [SerializeField] private List<Transform> platforms; // Lista de plataformas
    [SerializeField] private List<bool> initialDirections; // Direcciones iniciales (true = adelante, false = atr谩s)
    [SerializeField] private float moveSpeed = 20f;
    [SerializeField] private float separationSpeed = 5f; //  Velocidad reducida al colisionar

    private Dictionary<Transform, bool> movingForward = new Dictionary<Transform, bool>();
    private Dictionary<Transform, float> platformSpeeds = new Dictionary<Transform, float>(); //  Velocidad de cada plataforma

    private void Start()
    {
        if (platforms.Count != initialDirections.Count)
        {
            // Debug.LogError("Las listas de plataformas y direcciones iniciales deben tener el mismo tama帽o.");
            return;
        }

        // Asignamos la direcci贸n y velocidad inicial a cada plataforma
        for (int i = 0; i < platforms.Count; i++)
        {
            movingForward[platforms[i]] = initialDirections[i];
            platformSpeeds[platforms[i]] = moveSpeed;

            // Configurar el detector de colisiones
            PlatformCollisionDetector detector = platforms[i].GetComponentInChildren<PlatformCollisionDetector>();
            if (detector != null){
                detector.SetPlatformController(this, platforms[i]);
            }
        }


        if (PlatformEventManager.Instance != null){
            PlatformEventManager.Instance.OnPlatformReturn += ChangeDirection;
        }
    }

    private void Update(){
        MovePlatforms();
    }

    private void MovePlatforms(){
        foreach (Transform platform in platforms){
            float direction = movingForward[platform] ? 1 : -1;
            platform.position += Vector3.forward * direction * platformSpeeds[platform] * Time.fixedDeltaTime;
        }
    }

    private void ChangeDirection()
    {
        foreach (Transform platform in platforms)
        {
            movingForward[platform] = !movingForward[platform]; // Invertimos direcci贸n
            platformSpeeds[platform] = moveSpeed; //  Restauramos la velocidad normal
        }

        // Debug.Log("Todas las plataformas cambiaron de direcci贸n y restauraron velocidad.");
    }

    public void HandlePlatformCollision(Transform platform)
    {
        if (platforms.Contains(platform))
        {
            movingForward[platform] = !movingForward[platform];
            platformSpeeds[platform] = separationSpeed; //  Reducimos velocidad temporalmente
            // Debug.Log(platform.name + " choc贸 con otra plataforma. Reduciendo velocidad y cambiando direcci贸n.");
        }
    }

    private void OnDestroy()
    {
        if (PlatformEventManager.Instance != null)
        {
            PlatformEventManager.Instance.OnPlatformReturn -= ChangeDirection;
        }
    }
}
